name: On Merge Group

on:
  merge_group:

jobs:
  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: failure()
    timeout-minutes: 10
    permissions: {}
    steps: [{ run: exit 1 }]
    needs:
      - changes
      - terraform-lint
      - terraform-apply

  changes:
    uses: ./.github/workflows/wf-changes.yaml

  terraform-lint:
    name: Terraform Lint
    needs: [changes]
    if: ${{ needs.changes.outputs.terraform-targets != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.changes.outputs.terraform-targets) }}
    uses: ./.github/workflows/wf-terraform-lint.yaml
    with:
      target: ${{ matrix.target }}

  terraform-apply:
    name: Terraform Apply
    needs: [changes]
    if: ${{ needs.changes.outputs.terraform-targets != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.changes.outputs.terraform-targets) }}
    uses: tosuke-homelab/infra/.github/workflows/wf-terraform-apply.yaml@main
    with:
      target: ${{ matrix.target }}
    secrets: inherit
