name: On Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - dequeued

jobs:
  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    if: failure()
    timeout-minutes: 10
    permissions: {}
    steps: [{ run: exit 1 }]
    needs:
      - changes
      - terraform-lint
      - terraform-plan

  changes:
    uses: ./.github/workflows/wf-changes.yaml

  terraform-lint:
    name: Terraform Lint
    needs: [changes]
    if: ${{ needs.changes.outputs.terraform-targets != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.changes.outputs.terraform-targets) }}
    uses: ./.github/workflows/wf-terraform-lint.yaml
    with:
      target: ${{ matrix.target }}
  
  terraform-plan:
    name: Terraform Plan
    needs: [changes]
    if: ${{ needs.changes.outputs.terraform-targets != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJSON(needs.changes.outputs.terraform-targets) }}
    uses: ./.github/workflows/wf-terraform-plan.yaml
    with:
      target: ${{ matrix.target }}
    secrets:
      LINODE_PLAN_TOKEN: ${{ secrets.LINODE_PLAN_TOKEN }}
