name: Actionlint

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: dorny/paths-filter@0e4a8c6effa4802afeda77dc8d303f8176d7dfad # v3.0.4
        id: filter
        with:
          filters: |
            actionlint:
              - .github/workflows/**
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        if: ${{ steps.filter.outputs.actionlint == 'true' }}
        with:
          aqua_version: v2.53.3
      - name: Run actionlint
        if: ${{ steps.filter.outputs.actionlint == 'true' }}
        uses: suzuki-shunsuke/github-action-actionlint@4f0298e8f8b13fffbdc13207463d65e92205ad0c # v0.1.5




