name: Changes

on:
  workflow_call:
    outputs:
      terraform-targets:
        value: ${{ jobs.changes.outputs.terraform-targets }}

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      terraform-targets: ${{ steps.terraform-filter.outputs.changes }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: dorny/paths-filter@0e4a8c6effa4802afeda77dc8d303f8176d7dfad # v3.0.4
        id: terraform-filter
        with:
          filters: |
            gcloud:
              - aqua.yaml
              - .github/workflows/**
              - terraform/gcloud/**
            linode:
              - aqua.yaml
              - .github/workflows/**
              - terraform/linode/**
