name: Changes

on:
  workflow_call:
    outputs:
      terraform-targets:
        value: ${{ jobs.changes.outputs.terraform-targets }}

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      terraform-targets: ${{ steps.terraform-filter.outputs.changes }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: terraform-filter
        with:
          filters: |
            gcloud:
              - aqua.yaml
              - .github/workflows/**
              - terraform/gcloud/**
            linode:
              - aqua.yaml
              - .github/workflows/**
              - terraform/linode/**
