name: Terraform Lint

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        with:
          aqua_version: v2.50.1

      - name: Run tflint
        id: tflint
        continue-on-error: true
        uses: suzuki-shunsuke/github-action-tflint@a9d1f3376c8bbd6aadf4891dfe32f5e246c9c52f # v1.2.1
        with:
          working_directory: terraform/${{ inputs.target }}

      - name: Run tfsec
        id: tfsec
        continue-on-error: true
        uses: suzuki-shunsuke/github-action-tfsec@6b4afce3060c0d8865d269de0c5fabc90e1b20f7 # v1.0.0
        with:
          working_directory: terraform/${{ inputs.target }}
          
      - name: Check lint results
        if: steps.tflint.outcome == 'failure' || steps.tfsec.outcome == 'failure'
        run: |
          echo "::error::Terraform lint checks failed"
          exit 1
