name: Terraform Plan

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      LINODE_PLAN_TOKEN:
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    defaults:
      run:
        working-directory: terraform/${{ inputs.target }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.53.3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2.1.13
        with:
          workload_identity_provider: ${{ vars.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCLOUD_PLAN_SA }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan & PR Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINODE_TOKEN: ${{ secrets.LINODE_PLAN_TOKEN }}
        run: tfcmt plan --patch --skip-no-changes --var 'target:${{ inputs.target }}' -- terraform plan -no-color -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: tfplan-${{ inputs.target }}
          path: terraform/${{ inputs.target }}/tfplan
          retention-days: 14
