name: Terraform CI

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.1.2
        with:
          aqua_version: v2.50.0
      - name: Run tflint
        continue-on-error: true
        uses: suzuki-shunsuke/github-action-tflint@v1.2.1
        with:
          working_directory: terraform/${{ inputs.target }}
      - name: Run tfsec
        continue-on-error: true
        uses: suzuki-shunsuke/github-action-tfsec@v1.0.0
        with:
          working_directory: terraform/${{ inputs.target }}

  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    defaults:
      run:
        working-directory: terraform/${{ inputs.target }}
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.1.2
        with:
          aqua_version: v2.50.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCLOUD_PLAN_SA }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan & PR Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt plan --patch --skip-no-changes --var 'target:${{ inputs.target }}' -- terraform plan -no-color
