name: Terraform Plan

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
    secrets:
      LINODE_PLAN_TOKEN:
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    defaults:
      run:
        working-directory: terraform/${{ inputs.target }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
        with:
          aqua_version: v2.53.2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
        with:
          workload_identity_provider: ${{ vars.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCLOUD_PLAN_SA }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan & PR Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINODE_TOKEN: ${{ secrets.LINODE_PLAN_TOKEN }}
        run: tfcmt plan --patch --skip-no-changes --var 'target:${{ inputs.target }}' -- terraform plan -no-color -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: tfplan-${{ inputs.target }}
          path: terraform/${{ inputs.target }}/tfplan
          retention-days: 14
